name: Mi primer workflow de git hub actions
#controla cuando se ejecutar√° el workflow
on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]
jobs:
 saludo: 
  runs-on: ubuntu-latest
  steps:
   # paso1: imprimir un mensaje por consola
   -name: ejecutar un mensaje de bienvenida.
    run: echo "HOLA ISA"
   # paso2: 
    -name: mostrar fecha
     run: date
